### ISSUE TITLE
After you updated the script today, it's no longer working

### ISSUE THREAD

**Issue by ignasbogusis** [WindiestHook381/wh-robberies#1]
I tried everything, except editing your code, script throws the error that export createSafe doesn't even exist. At first i thought it was because I renamed the file name, but after changing it back still getting this error.

![image](https://user-images.githubusercontent.com/57500389/88484686-1182d200-cf79-11ea-96f2-f3038e589e70.png)

**Comment by WindiestHook381** [comment]
Make sure the name has remained the same: wh-robberies
